# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Generate firmware decryption json file

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0,3,5,7,10,12,14,16,18,20 * * *'
  repository_dispatch:
    types: [telegram_trigger]  
jobs:
  decrypt:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install python dependencies
      run: |
        pip install -r requirements.txt
    - name: Run decryption script
      env:
        DATABASE: ${{ secrets.DATABASE }}
        HOST: ${{ secrets.HOST }}
        DBUSER: ${{ secrets.DBUSER }}
        PASSWORD: ${{ secrets.PASSWORD }}
        FCM_API_KEY: ${{ secrets.FCM_API_KEY }}
        FCM_KEY: ${{ secrets.FCM_KEY }}
        TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        TG_USER_ID: ${{ secrets.TG_USER_ID }}
        TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
      run: |
        python samsung_test_firmware_decrypt.py
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update json files"
          title: "Update firmware decryption json files"
          body: |
            Auto-generated PR to update firmware decryption json files.
            
            Generated at: ${{ github.run_id }}
            Workflow: ${{ github.workflow }}
          branch: firmware-update-${{ github.run_number }}
          base: master
          delete-branch: true
          author: ${{ secrets.USERNAME }} <${{ secrets.USEREMAIL }}>
