# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Generate firmware decryption json file

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0,3,5,7,10,12,14,16,18,20 * * *'
  repository_dispatch:
    types: [telegram_trigger]  
jobs:
  decrypt:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install python dependencies
      run: |
        pip install -r requirements.txt
    - name: Run decryption script
      env:
        DATABASE: ${{ secrets.DATABASE }}
        HOST: ${{ secrets.HOST }}
        DBUSER: ${{ secrets.DBUSER }}
        PASSWORD: ${{ secrets.PASSWORD }}
        FCM_API_KEY: ${{ secrets.FCM_API_KEY }}
        FCM_KEY: ${{ secrets.FCM_KEY }}
        TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        TG_USER_ID: ${{ secrets.TG_USER_ID }}
        TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
      run: |
        python samsung_test_firmware_decrypt.py
    - name: Stage and commit
      run: |
          git config --global user.name ${{ secrets.USERNAME }}
          git config --global user.email ${{ secrets.USEREMAIL }}
          export TZ='Asia/Shanghai'
          git add .
          git commit -m "Update json files" -a
    - name: Push json files
      uses: ad-m/github-push-action@master
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
